version: '3'
services:
  api:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: laravel-docker
    ports:
      - 8080:80
    depends_on:
      - mysqldb
    volumes:
      - .:/srv/app
    # container_name:
  mysqldb:
    image: mysql:5.7
    container_name: mysqldb
    command: mysqld --user=root --verbose
    volumes:
       - ./schemadump.sql:/docker-entrypoint-initdb.d/schemadump.sql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "sasquatch"
      MYSQL_USER: "sasquatch"
      MYSQL_PASSWORD: "sasquatch"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
